[build]
builder = "nixpacks"
buildCommand = "npm run db:generate && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/auth/me"
restartPolicyType = "on_failure"

[[services]]
name = "game-admin"
